name: 'hermit-bench'
author: 'Carl Wachter'
description: 'Runs benchmarks on Hermit, which are given in a JSON file'
branding:
  icon: activity
  color: red

inputs:
  benchmark-file:
    description: 'Path to the benchmark JSON file'
    required: true
  build-command:
    description: 'Command to build the project'
    required: true
  benchmark-build:
    description: 'Whether to benchmark the build process'
    default: 'false'
    required: false

outputs:
  result-file:
    description: 'Path to the result JSON file'
    value: ${{ steps.run-bench.outputs.results-path }}

runs:
  using: 'composite'
  steps:
    - name: Build
      run: |
        cd ../../_actions/hermit-os/hermit-bench/kernel
        ln -s ../../../../kernel/kernel/rust-toolchain.toml rust-toolchain.toml
        cargo build --package hermit-bench
      shell: bash
    - name: Run benchmarks
      id: run-bench
      run: |
        cd ../../_actions/hermit-os/hermit-bench/kernel
        cargo run ${{ inputs.benchmark-file }} ../../../../kernel/kernel "${{ inputs.build-command }}" ${{ inputs.benchmark-build }}
        echo "results-path=../results.json" >> $GITHUB_OUTPUT
      shell: bash