name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install Toolchain
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Run action
        uses: ./
        id: run-action
        with:
          benchmark-file: input.yml
          path-to-repo: .github/test
          path-to-action: .
      - name: Validate results
        run: |
          cd .github/validate
          cargo run ../test/${{ steps.run-action.outputs.result-file }}
        shell: bash

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add clippy
      - run: cargo clippy

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - run: cargo fmt --all --check